version: '3'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: public
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  # reedbricks-data:
  db-data: