export enum ApiStatus {
  API_FAIL = 0,
  API_SUCCESS = 1,
  USER_FOUND = 2,
  USER_NOT_FOUND = 3,
  USER_ALREADY_EXIST = 4,
  USER_NOT_EXIST = 5,

  REQUEST_CREATED = 6,
  REQUEST_UPDATED = 7,
  REQUEST_DELETED = 8,
  REQUEST_NOT_FOUND = 9,
  

  API_BAD_REQUEST = 400,

  USERS_FOUND = 10,
  USERS_NOT_FOUND = 11,
}
